### ISSUE TITLE
Add support for an unbalanced tree

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/merkle-tree#3]
At the moment the number of leaves must be a power of 2.

**Comment by noamnelke** [comment]
Going to implement [this](https://adc.sourceforge.io/draft-jchapweske-thex-02.html#anchor4) approach.

In the simplest case, a single leaf is added to a previously complete tree:
![image](https://user-images.githubusercontent.com/776358/53988345-ec938200-412b-11e9-8b2a-bc0ec7331f26.png)

This leaf is used as a direct right child to the new root, the previous root being the left child.

If more than one additional leaf is added to a complete tree some internal nodes are calculable and should therefore be used. Here's a simple example:
![image](https://user-images.githubusercontent.com/776358/53989522-d3400500-412e-11e9-8a6d-4d876db1a594.png)

Here, the parent of the two additional leaves is used as a direct left child of the new root.

In some cases intermediate internal nodes have to be calculated and aggregated into the new root, as in this example:
![image](https://user-images.githubusercontent.com/776358/53989646-1c905480-412f-11e9-95d2-b7fc67614df3.png)

The orange bordered node on the 4th layer was calculated from two lower nodes and then used to calculate the root.

The worst case, in terms of required calculations to reach the root from an unbalanced tree, is the case where a single leaf is missing to make the tree balanced again:
![image](https://user-images.githubusercontent.com/776358/53989871-a7714f00-412f-11e9-851d-acec90b6daeb.png)

In this case `log(N)-1` nodes need to be calculated to reach the root.

It's worth referring to [this discussion](https://crypto.stackexchange.com/questions/2106/what-is-the-purpose-of-using-different-hash-functions-for-the-leaves-and-interna?rq=1) for some security considerations: if the same hashing function is used for leaves and internal nodes then this approach is susceptible to a second preimage attack. This attack is not exploitable in the intended use cases for Spacemesh PoST and PoET, but is out of scope of this library, anyway, since we leave leaf hashing to the invoking code. We should add a note about this in the documentation to prevent security vulnerabilities in 3rd party calling code.

**Comment by moshababo** [comment]
Sounds good. Make sure to clarify (also with test code) that different hash functions can be applied by prepending of 0x00 byte for a leaf node, and 0x01 byte for an internal node. Otherwise it might sound that a different hash algorithm is needed.

**Comment by noamnelke** [comment]
I've implemented this but haven't pushed yet, since the existing validation only works in half the cases and needs to be modified slightly.

Why half the cases, you ask? Great question!

If the promoted node happens to be a right child of its parent generating its parent just works, but if it happens to be a left child hashing happens in the wrong order since it should always be used as a right child (see the explanation above).

But how do we detect a promotion at validation time?

No additional information is required and we can use the same proof to derive this information.

Since promoted nodes are always on the right side of the tree, we can use the proven leaf's index to learn the height of the tree and expected number of proof nodes. By comparing that to the actual number of proof nodes we can understand which nodes have been promoted and how much.

Implementation of this coming soon.

**Comment by noamnelke** [comment]
Eventually implemented by padding with zero-filled nodes.

Resolved by https://github.com/spacemeshos/merkle-tree/pull/5
